name: "GitOps"

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: "Type 'destroy' to confirm resource destruction"
        required: true
  push:
    branches:
      - main
      - stage
    paths:
      - terraform/**
  pull_request:
    branches:
      - main
    paths:
      - terraform/**

env:
  # Credentials for deployment to AWS
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  # S3 bucket for the Terraform state
  BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }}
  AWS_REGION: us-east-2
  EKS_CLUSTER: kels-eks

jobs:
  terraform:
    name: "Apply Terraform Code Changes"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
      # Step 1: Checkout source code
      - name: Checkout Source Code
        uses: actions/checkout@v4

      # Step 2: Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Step 3: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.3

      # Step 4: Initialize Terraform
      - name: Terraform Init
        id: init
        run: |
          terraform init -reconfigure \
            -backend-config="bucket=${{ env.BUCKET_TF_STATE }}" \
            -backend-config="key=terraform/state" \
            -backend-config="region=${{ env.AWS_REGION }}"

      # Step 5: Format Terraform Files
      - name: Terraform Format
        id: fmt
        run: terraform fmt

      # Step 6: Validate Terraform Files
      - name: Terraform Validate
        id: validate
        run: terraform validate

      # Step 7: Create Terraform Plan
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false -out planfile
        continue-on-error: true

      # Step 8: Check Terraform Plan Status
      - name: Terraform Plan Status Check
        if: steps.plan.outcome == 'failure'
        run: exit 1

      # Step 9: Apply Terraform Plan (Only for pushes)
      - name: Terraform apply
        id: apply
        # if: github.event_name == 'push'
        run: terraform destroy -auto-approve -input=false -parallelism=1 planfile

      # Step 10: Get kubeconfig for EKS
      - name: Get Kubeconfig File
        id: getconfig
        if: steps.apply.outcome == 'success'
        run: aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.EKS_CLUSTER }}

      # Step 11: Install Ingress Controller
      - name: Install Ingress Controller
        if: steps.apply.outcome == 'success' && steps.getconfig.outcome == 'success'
        run: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.1.3/deploy/static/provider/aws/deploy.yaml

      # Step 12: Destroy Terraform Resources (Triggered by Workflow Dispatch)
      - name: Terraform Destroy
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.confirm == 'destroy'
        run: terraform destroy -auto-approve -input=false
